"""Уникальные поля для названия отеля

Revision ID: d3013ccf03ab
Revises: 696e06b06d0e
Create Date: 2026-02-09 15:52:19.774874

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d3013ccf03ab"
down_revision: Union[str, Sequence[str], None] = "696e06b06d0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "hotels", ["title"])
    op.create_unique_constraint(None, "hotels", ["location"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "hotels", type_="unique")
    op.drop_constraint(None, "hotels", type_="unique")
    # ### end Alembic commands ###
