"""rooms remove unique title

Revision ID: 92354143fe14
Revises: 72f289919203
Create Date: 2026-02-09 19:55:24.615560

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "92354143fe14"
down_revision: Union[str, Sequence[str], None] = "72f289919203"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("rooms_title_key"), "rooms", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("rooms_title_key"), "rooms", ["title"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
