"""facilities add title unique

Revision ID: 696e06b06d0e
Revises: 704ae6a1cb32
Create Date: 2026-02-03 20:30:44.480037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "696e06b06d0e"
down_revision: Union[str, Sequence[str], None] = "704ae6a1cb32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "facilities", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "facilities", type_="unique")
    # ### end Alembic commands ###
