"""Уникальное поле только  для названия отеля

Revision ID: 3fe7f55ff329
Revises: d3013ccf03ab
Create Date: 2026-02-09 16:08:59.909811

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3fe7f55ff329"
down_revision: Union[str, Sequence[str], None] = "d3013ccf03ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("hotels_location_key"), "hotels", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("hotels_location_key"),
        "hotels",
        ["location"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
