"""Add ondelete=CASCADE to model rooms and bookings

Revision ID: 9e6223f27fc9
Revises: 2edcae9b025a
Create Date: 2026-02-10 17:35:01.424162

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e6223f27fc9"
down_revision: Union[str, Sequence[str], None] = "2edcae9b025a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("bookings_room_id_fkey"), "bookings", type_="foreignkey")
    op.drop_constraint(op.f("bookings_user_id_fkey"), "bookings", type_="foreignkey")
    op.create_foreign_key(
        None, "bookings", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "bookings", "rooms", ["room_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("rooms_hotel_id_fkey"), "rooms", type_="foreignkey")
    op.create_foreign_key(
        None, "rooms", "hotels", ["hotel_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rooms", type_="foreignkey")
    op.create_foreign_key(
        op.f("rooms_hotel_id_fkey"), "rooms", "hotels", ["hotel_id"], ["id"]
    )
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.create_foreign_key(
        op.f("bookings_user_id_fkey"), "bookings", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("bookings_room_id_fkey"), "bookings", "rooms", ["room_id"], ["id"]
    )
    # ### end Alembic commands ###
